### ISSUE TITLE
Translate the site to Portuguese

### ISSUE THREAD

**Issue by stevenvergenz** [stevenvergenz/dfrpg-toonstore#48]
At the time of this writing, about 5% of the ToonStore traffic is from Brazil, I think they'd appreciate a native language version.

In progress by @Atmo26.

**Comment by stevenvergenz** [comment]
Estimated at 58% complete at last check.

**Comment by Atmo26** [comment]
I'm doing my part the fast as I can, as college is giving me white hair and
some problems with bills arose from nowhere. Don't worry, I'm doing my best
to finish this.

2015-03-04 12:19 GMT-03:00 Steven Vergenz <notifications@github.com>:

> Estimated at 58% complete at last check.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stevenvergenz/dfrpg-toonstore/issues/48#issuecomment-77176548>
> .
>



-- 
Gosta de 3D&T, RPG, animes e coisas legais de hoje em dia? Acesse
www.atmoland.blogspot.com e divirta-se!

**Comment by stevenvergenz** [comment]
Don't worry about it, it's done when it's done. Just writing up this issue in case someone wants to help you.

**Comment by stevenvergenz** [comment]
And the translation is done! Well, done enough for now. It'll be going live shortly, so make sure to proof-read it.
