### ISSUE TITLE
Sheet Duplication Not Working

### ISSUE THREAD

**Issue by dman8297** [stevenvergenz/dfrpg-toonstore#53]
I've spent several hours trying to copy some sheets for NPC's I'm using for a session this weekend but every time I try to copy the sheet I get a blank page that says

"TypeError: /home/toonstore/dfrpg-toonstore/templates/newtoon.jade:38
    36| 				select#template(name='template')
    37| 					option
  > 38| 					for item in templates
    39| 						option(value='#{item}', label='#{item}')= item
    40| 				p.caption= __('newtoon.template.caption')
    41| 

Cannot read property 'length' of undefined"

Will appreciate any help you can give me. Other than that I'm loving the site. the templates have saved a lot of time for me and my players and is the site in general is very easy to use.

**Comment by stevenvergenz** [comment]
Hey dman, thanks for reporting this. I was able to duplicate a couple of my characters just fine, and couldn't reproduce this error. Could you give me some more info about the circumstances of the error?

Mostly I need to know what user you were logged in as, and what character(s) you were trying to copy. It'd also be nice to know what browser you were using, and roughly when you were receiving the error (so I can check the server logs).

One other thing, make sure your cache is clear when you access the page. On most browsers you can do this by hitting Ctrl-F5 to force a refresh.

I look forward to hearing back from you, I want to get this resolved as quickly as you do. Cheers!

**Comment by dman8297** [comment]
Steven,
I am logged in as DylboScratchins. I've been trying to copy the sheets for
some generic NPC's, namely some thug like characters and a boss like
character. I just tried duplicating my WC Vampire, Marth, at 10:40 AM, EST.
I've been using Chrome and I just tried Firefox and received the same
error. I've attached a screenshot of the error to this email. Maybe you can
make more sense of the issue with that, I have no idea. Clearing the cache
before, and after, duplication didn't seem to help the issue.

On Wed, Mar 11, 2015 at 8:39 AM, Steven Vergenz <notifications@github.com>
wrote:

> Hey dman, thanks for reporting this. I was able to duplicate a couple of
> my characters just fine, and couldn't reproduce this error. Could you give
> me some more info about the circumstances of the error?
>
> Mostly I need to know what user you were logged in as, and what
> character(s) you were trying to copy. It'd also be nice to know what
> browser you were using, and roughly when you were receiving the error (so I
> can check the server logs).
>
> One other thing, make sure your cache is clear when you access the page.
> On most browsers you can do this by hitting Ctrl-F5 to force a refresh.
>
> I look forward to hearing back from you, I want to get this resolved as
> quickly as you do. Cheers!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stevenvergenz/dfrpg-toonstore/issues/53#issuecomment-78254968>
> .
>



-- 
Thanks for reading~

Dylan

**Comment by stevenvergenz** [comment]
Aha, I've figured it out! So the actual form for the new character comes up, but when you submit you get that error, am I right? When you duplicate the character, make sure you change the short link to something different or it won't work. The error message that normally shows up if you don't change it is actually the part that's throwing that problem.

If you change that field to something unique, it will work. That should get you by until I can fix that problem.

**Comment by stevenvergenz** [comment]
Great, I think it's fixed. Clear your cache and try again?

**Comment by dman8297** [comment]
Yes! Thank you so much. Nice to have such dedicated support.

On Wed, Mar 11, 2015 at 1:21 PM, Steven Vergenz <notifications@github.com>
wrote:

> Closed #53 <https://github.com/stevenvergenz/dfrpg-toonstore/issues/53>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stevenvergenz/dfrpg-toonstore/issues/53#event-250276743>
> .
>



-- 
Thanks for reading~

Dylan
