### ISSUE TITLE
Add "shapeshifted" toggle to Stress Pane

### ISSUE THREAD

**Issue by supahseppe** [stevenvergenz/dfrpg-toonstore#58]
A toggle with similar functionality to the 'shapeshifter' toggle on the skills pane should be implemented on the stress pane, for similar reasons.

**Comment by stevenvergenz** [comment]
I think I've got it working as of 9997b25. Test it out, and I'll push it live tomorrow probably.

**Comment by stevenvergenz** [comment]
A couple things wrong: toggling shifted status marks stress panel as dirty, and the stress panel should have a shifter button too. I'll try to fix these soon.

**Comment by stevenvergenz** [comment]
Completed as of 2103611
