### ISSUE TITLE
Were Forms missing Skills

### ISSUE THREAD

**Issue by rlugge** [stevenvergenz/dfrpg-toonstore#61]
Expected behavior: A were-form template character should have all skills in their available skills lists, in both forms.

Current behavior: Currently, were-form template characters have zero skills in their skill list in shifted form.  Instead of being able to drag and drop skills, you have to add a skill, then drag it up to the appropriate level.

Desired change: Copy the skill list from 'normal' form over to 'animal' form skills.

**Comment by stevenvergenz** [comment]
Is this bug talking exclusively about the template, or about the shapeshifting mechanic?

**Comment by stevenvergenz** [comment]
I've copied the skills over for the template, but I'm gonna leave this issue open. I'm gonna add a "Copy skills from human form" button for future convenience.
