### ISSUE TITLE
Setting Toughness To 0 is Rejected

### ISSUE THREAD

**Issue by rlugge** [stevenvergenz/dfrpg-toonstore#62]
Expected result:  If you have a toughness value on a stress track, then set it to 0, the new value should be accepted and saved.
Current result:  If you have a toughness value set, then try to change it to 0, the new value is ignored and the old value preserved, to be seen on a reload.
Difference:  Make the system accept a value of 0.

**Comment by stevenvergenz** [comment]
Ah, you're right. Perhaps more importantly, it breaks completely when you set it negative. The bounds checking is off. Thanks for the report, I'll fix this ASAP.
