### ISSUE TITLE
Incorrect stress, human-form-only skills when printing shapeshifter characters

### ISSUE THREAD

**Issue by macmaxbh** [stevenvergenz/dfrpg-toonstore#63]
Just discovered ToonStore yesterday--it's pretty snazzy, thanks for making it and making it publicly accessible!

I put in [my shapeshifter character](https://toonstore.net/macmaxbh/strickland/) and do like the human/other switcher. I was trying to print out a copy for my DM's reference (she had paper copies of everyone else) and noticed that my stress track didn't come through properly (I should have four physical, in both forms; I'm seeing the default two); and that I'm only seeing my human-form skills. 

Since my stress is the same in both forms I was more interested in making sure both sets of skills showed up (particularly as that's what is done on the official form as well) and making sure at least one form's stress was accurately represented. 

My web development skills are extremely rusty (it's been over five years since I've touched anything JS or CSS; and never node.js), but I could try to fork and come up with a fix if you're too busy.

**Comment by stevenvergenz** [comment]
Huh, you're right, that's odd. Let me look into it and get back to you. That printable page doesn't get tested as thoroughly as the main page, I'm surprised it works at all some days :p

**Comment by stevenvergenz** [comment]
It's fixed. Thanks for reporting this, hope you and your group get some mileage out of it :)

**Comment by macmaxbh** [comment]
Awesome. Stress track is definitely fixed. Thanks for the ridiculously quick fix!

My other question, which is more on the 'feature-request' side of the spectrum, was to get a second skills block similar to the [official shapeshifter character sheet](http://www.evilhat.com/home/wp-content/uploads/2010/03/Shapeshifter-Sheet.pdf) that lists the skills in the changed form explicitly. Is that better in a separate issue and/or something I should try my own hand at?

**Comment by stevenvergenz** [comment]
Well, the printable sheet really wasn't intended to be used exclusively, only as quick reference to the full site. And since my group isn't playing Dresden anymore, I don't plan on adding any new features any time soon. You're welcome to take a crack at adding it if you want. The printable page template is at [/templates/jade/printable.jade](https://github.com/stevenvergenz/dfrpg-toonstore/blob/master/templates/jade/printable.jade).

**Comment by macmaxbh** [comment]
No problem at all; makes a lot of sense. I really appreciate you fixing the stress track and I'll see if I can take a crack at the printable template myself. Thanks again!
